name: ABCproject_pipelineinGithubactions

on:
  push: 
   branches: 
    - main
  workflow_dispatch: 
  
jobs:
  build:
   runs-on: ubuntu-latest
   
   steps:
     - name: checkout code
     uses: actions/checkout@V1
     
     - name: print present working directory
      run: pwd
      
     - name: print list of directories
      run: ls
      
     - name: date of the day
      run: date
     
