name: ABCproject_pipelineinGithubactions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print present working directory
        run: pwd

      - name: Print list of directories
        run: ls

      - name: Date of the day
        run: date
      
